# TAK.gov GitLab CI/CD Pipeline for ATAK Plugin
# Based on working HelloWorld sample configuration

default:
  image: ${TAK_REGISTRY_HOST}/devsecops/android-builder-image:17-${ANDROID_BUILDER_TAG}

include:
  - project: 'devsecops/gitlab-ci-common'
    ref: master
    file: '/template/build_and_sign.yml'
  - project: 'devsecops/gitlab-ci-common'
    ref: master
    file: '/template/artifactory_token_service.yml'

variables:
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: none  # No submodules needed
  ATAK_CI: "1"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"
  # Credentials should be set as CI/CD variables in GitLab project settings
  # TAKREPO_USER and TAKREPO_PASSWORD will be read from environment

stages:
  - build
  - test
  - package
  - production
  
# Cache Gradle dependencies
cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .gradle/
    - build/
    - app/build/

# Base job for building plugin - using direct credentials
.assemblePlugin:
  stage: build
  before_script:
    - chmod +x gradlew
    # Use CI/CD variables for credentials (set in GitLab project settings)
    # Use /tak/ virtual repository which includes all TAK repositories
    - export TAKREPO_URL="${ARTIFACTORY_URL_APK:-https://artifacts.tak.gov/artifactory/tak}"
    - export TAKREPO_USER="${TAKREPO_USER}"
    - export TAKREPO_PASS="${TAKREPO_PASSWORD}"
    # Debug output
    - echo "Using repository URL: ${TAKREPO_URL}"
    - echo "Using user: ${TAKREPO_USER}"
    # Create local.properties with credentials
    - |
      cat > local.properties << EOF
      sdk.dir=${ANDROID_SDK_ROOT:-/opt/android-sdk}
      takrepo.url=${TAKREPO_URL}
      takrepo.user=${TAKREPO_USER}
      takrepo.password=${TAKREPO_PASS}
      EOF
  script:
    - ./gradlew -Pci --console=plain -Ptakrepo.url="${TAKREPO_URL}" -Ptakrepo.user="${TAKREPO_USER}" -Ptakrepo.password="${TAKREPO_PASS}" ${ASSEMBLE_GRADLE_TASK}
  artifacts:
    expire_in: 720h
    paths:
      - app/build/outputs/

# Build variants - matching HelloWorld pattern
assembleMilSdk:
  extends: .assemblePlugin
  variables:
    ASSEMBLE_GRADLE_TASK: assembleMilDebug

assembleMilOdk:
  extends: .assemblePlugin
  variables:
    ASSEMBLE_GRADLE_TASK: assembleMilRelease
  
assembleCivSdk:
  extends: .assemblePlugin
  variables:
    ASSEMBLE_GRADLE_TASK: assembleCivDebug

assembleCivOdk:
  extends: .assemblePlugin
  variables:
    ASSEMBLE_GRADLE_TASK: assembleCivRelease

# Production build with signing
assembleProduction:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^maintenance/'
      when: always
    - if: '$CI_COMMIT_BRANCH !~ /^maintenance/'
      when: manual
      allow_failure: true 
  stage: production
  extends: .build_and_sign_jdk17

# Test job
testRelease:
  stage: test
  before_script:
    - chmod +x gradlew
    - export TAKREPO_URL="${ARTIFACTORY_URL_APK:-https://artifacts.tak.gov/artifactory/tak}"
    - export TAKREPO_USER="${TAKREPO_USER}"
    - export TAKREPO_PASS="${TAKREPO_PASSWORD}"
  script:
    - ./gradlew -Pci --console=plain -Ptakrepo.url="${TAKREPO_URL}" -Ptakrepo.user="${TAKREPO_USER}" -Ptakrepo.password="${TAKREPO_PASS}" :app:testCivRelease
  when: manual


