// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.atakmap.android.sampledetailtester.proto;

/**
 * Protobuf type {@code com.atakmap.android.sampledetailtester.proto.Student}
 */
public  final class Student extends
    com.google.protobuf.GeneratedMessageLite<
        Student, Student.Builder> implements
    // @@protoc_insertion_point(message_implements:com.atakmap.android.sampledetailtester.proto.Student)
    StudentOrBuilder {
  private Student() {
    firstname_ = "";
    surname_ = "";
    period_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int FIRSTNAME_FIELD_NUMBER = 1;
  private java.lang.String firstname_;
  /**
   * <code>string firstname = 1;</code>
   */
  public java.lang.String getFirstname() {
    return firstname_;
  }
  /**
   * <code>string firstname = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFirstnameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(firstname_);
  }
  /**
   * <code>string firstname = 1;</code>
   */
  private void setFirstname(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    firstname_ = value;
  }
  /**
   * <code>string firstname = 1;</code>
   */
  private void clearFirstname() {
    
    firstname_ = getDefaultInstance().getFirstname();
  }
  /**
   * <code>string firstname = 1;</code>
   */
  private void setFirstnameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    firstname_ = value.toStringUtf8();
  }

  public static final int SURNAME_FIELD_NUMBER = 2;
  private java.lang.String surname_;
  /**
   * <code>string surname = 2;</code>
   */
  public java.lang.String getSurname() {
    return surname_;
  }
  /**
   * <code>string surname = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSurnameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(surname_);
  }
  /**
   * <code>string surname = 2;</code>
   */
  private void setSurname(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    surname_ = value;
  }
  /**
   * <code>string surname = 2;</code>
   */
  private void clearSurname() {
    
    surname_ = getDefaultInstance().getSurname();
  }
  /**
   * <code>string surname = 2;</code>
   */
  private void setSurnameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    surname_ = value.toStringUtf8();
  }

  public static final int GRADE_FIELD_NUMBER = 3;
  private int grade_;
  /**
   * <code>int32 grade = 3;</code>
   */
  public int getGrade() {
    return grade_;
  }
  /**
   * <code>int32 grade = 3;</code>
   */
  private void setGrade(int value) {
    
    grade_ = value;
  }
  /**
   * <code>int32 grade = 3;</code>
   */
  private void clearGrade() {
    
    grade_ = 0;
  }

  public static final int PERIOD_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<com.atakmap.android.sampledetailtester.proto.Period> period_;
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  public java.util.List<com.atakmap.android.sampledetailtester.proto.Period> getPeriodList() {
    return period_;
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  public java.util.List<? extends com.atakmap.android.sampledetailtester.proto.PeriodOrBuilder> 
      getPeriodOrBuilderList() {
    return period_;
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  public int getPeriodCount() {
    return period_.size();
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  public com.atakmap.android.sampledetailtester.proto.Period getPeriod(int index) {
    return period_.get(index);
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  public com.atakmap.android.sampledetailtester.proto.PeriodOrBuilder getPeriodOrBuilder(
      int index) {
    return period_.get(index);
  }
  private void ensurePeriodIsMutable() {
    if (!period_.isModifiable()) {
      period_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(period_);
     }
  }

  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  private void setPeriod(
      int index, com.atakmap.android.sampledetailtester.proto.Period value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensurePeriodIsMutable();
    period_.set(index, value);
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  private void setPeriod(
      int index, com.atakmap.android.sampledetailtester.proto.Period.Builder builderForValue) {
    ensurePeriodIsMutable();
    period_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  private void addPeriod(com.atakmap.android.sampledetailtester.proto.Period value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensurePeriodIsMutable();
    period_.add(value);
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  private void addPeriod(
      int index, com.atakmap.android.sampledetailtester.proto.Period value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensurePeriodIsMutable();
    period_.add(index, value);
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  private void addPeriod(
      com.atakmap.android.sampledetailtester.proto.Period.Builder builderForValue) {
    ensurePeriodIsMutable();
    period_.add(builderForValue.build());
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  private void addPeriod(
      int index, com.atakmap.android.sampledetailtester.proto.Period.Builder builderForValue) {
    ensurePeriodIsMutable();
    period_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  private void addAllPeriod(
      java.lang.Iterable<? extends com.atakmap.android.sampledetailtester.proto.Period> values) {
    ensurePeriodIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, period_);
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  private void clearPeriod() {
    period_ = emptyProtobufList();
  }
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  private void removePeriod(int index) {
    ensurePeriodIsMutable();
    period_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!firstname_.isEmpty()) {
      output.writeString(1, getFirstname());
    }
    if (!surname_.isEmpty()) {
      output.writeString(2, getSurname());
    }
    if (grade_ != 0) {
      output.writeInt32(3, grade_);
    }
    for (int i = 0; i < period_.size(); i++) {
      output.writeMessage(4, period_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!firstname_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getFirstname());
    }
    if (!surname_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getSurname());
    }
    if (grade_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, grade_);
    }
    for (int i = 0; i < period_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, period_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  public static com.atakmap.android.sampledetailtester.proto.Student parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.atakmap.android.sampledetailtester.proto.Student parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.atakmap.android.sampledetailtester.proto.Student prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code com.atakmap.android.sampledetailtester.proto.Student}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.atakmap.android.sampledetailtester.proto.Student, Builder> implements
      // @@protoc_insertion_point(builder_implements:com.atakmap.android.sampledetailtester.proto.Student)
      com.atakmap.android.sampledetailtester.proto.StudentOrBuilder {
    // Construct using com.atakmap.android.sampledetailtester.proto.Student.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string firstname = 1;</code>
     */
    public java.lang.String getFirstname() {
      return instance.getFirstname();
    }
    /**
     * <code>string firstname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      return instance.getFirstnameBytes();
    }
    /**
     * <code>string firstname = 1;</code>
     */
    public Builder setFirstname(
        java.lang.String value) {
      copyOnWrite();
      instance.setFirstname(value);
      return this;
    }
    /**
     * <code>string firstname = 1;</code>
     */
    public Builder clearFirstname() {
      copyOnWrite();
      instance.clearFirstname();
      return this;
    }
    /**
     * <code>string firstname = 1;</code>
     */
    public Builder setFirstnameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFirstnameBytes(value);
      return this;
    }

    /**
     * <code>string surname = 2;</code>
     */
    public java.lang.String getSurname() {
      return instance.getSurname();
    }
    /**
     * <code>string surname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      return instance.getSurnameBytes();
    }
    /**
     * <code>string surname = 2;</code>
     */
    public Builder setSurname(
        java.lang.String value) {
      copyOnWrite();
      instance.setSurname(value);
      return this;
    }
    /**
     * <code>string surname = 2;</code>
     */
    public Builder clearSurname() {
      copyOnWrite();
      instance.clearSurname();
      return this;
    }
    /**
     * <code>string surname = 2;</code>
     */
    public Builder setSurnameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSurnameBytes(value);
      return this;
    }

    /**
     * <code>int32 grade = 3;</code>
     */
    public int getGrade() {
      return instance.getGrade();
    }
    /**
     * <code>int32 grade = 3;</code>
     */
    public Builder setGrade(int value) {
      copyOnWrite();
      instance.setGrade(value);
      return this;
    }
    /**
     * <code>int32 grade = 3;</code>
     */
    public Builder clearGrade() {
      copyOnWrite();
      instance.clearGrade();
      return this;
    }

    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public java.util.List<com.atakmap.android.sampledetailtester.proto.Period> getPeriodList() {
      return java.util.Collections.unmodifiableList(
          instance.getPeriodList());
    }
    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public int getPeriodCount() {
      return instance.getPeriodCount();
    }/**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public com.atakmap.android.sampledetailtester.proto.Period getPeriod(int index) {
      return instance.getPeriod(index);
    }
    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public Builder setPeriod(
        int index, com.atakmap.android.sampledetailtester.proto.Period value) {
      copyOnWrite();
      instance.setPeriod(index, value);
      return this;
    }
    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public Builder setPeriod(
        int index, com.atakmap.android.sampledetailtester.proto.Period.Builder builderForValue) {
      copyOnWrite();
      instance.setPeriod(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public Builder addPeriod(com.atakmap.android.sampledetailtester.proto.Period value) {
      copyOnWrite();
      instance.addPeriod(value);
      return this;
    }
    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public Builder addPeriod(
        int index, com.atakmap.android.sampledetailtester.proto.Period value) {
      copyOnWrite();
      instance.addPeriod(index, value);
      return this;
    }
    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public Builder addPeriod(
        com.atakmap.android.sampledetailtester.proto.Period.Builder builderForValue) {
      copyOnWrite();
      instance.addPeriod(builderForValue);
      return this;
    }
    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public Builder addPeriod(
        int index, com.atakmap.android.sampledetailtester.proto.Period.Builder builderForValue) {
      copyOnWrite();
      instance.addPeriod(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public Builder addAllPeriod(
        java.lang.Iterable<? extends com.atakmap.android.sampledetailtester.proto.Period> values) {
      copyOnWrite();
      instance.addAllPeriod(values);
      return this;
    }
    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public Builder clearPeriod() {
      copyOnWrite();
      instance.clearPeriod();
      return this;
    }
    /**
     * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
     */
    public Builder removePeriod(int index) {
      copyOnWrite();
      instance.removePeriod(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.atakmap.android.sampledetailtester.proto.Student)
  }
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.atakmap.android.sampledetailtester.proto.Student();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        period_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        com.atakmap.android.sampledetailtester.proto.Student other = (com.atakmap.android.sampledetailtester.proto.Student) arg1;
        firstname_ = visitor.visitString(!firstname_.isEmpty(), firstname_,
            !other.firstname_.isEmpty(), other.firstname_);
        surname_ = visitor.visitString(!surname_.isEmpty(), surname_,
            !other.surname_.isEmpty(), other.surname_);
        grade_ = visitor.visitInt(grade_ != 0, grade_,
            other.grade_ != 0, other.grade_);
        period_= visitor.visitList(period_, other.period_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(tag, input)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                firstname_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                surname_ = s;
                break;
              }
              case 24: {

                grade_ = input.readInt32();
                break;
              }
              case 34: {
                if (!period_.isModifiable()) {
                  period_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(period_);
                }
                period_.add(
                    input.readMessage(com.atakmap.android.sampledetailtester.proto.Period.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (com.atakmap.android.sampledetailtester.proto.Student.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:com.atakmap.android.sampledetailtester.proto.Student)
  private static final com.atakmap.android.sampledetailtester.proto.Student DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Student();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static com.atakmap.android.sampledetailtester.proto.Student getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Student> PARSER;

  public static com.google.protobuf.Parser<Student> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

