// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.atakmap.android.sampledetailtester.proto;

public final class StudentOuterClass {
  private StudentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
