// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.atakmap.android.sampledetailtester.proto;

public interface PeriodOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.atakmap.android.sampledetailtester.proto.Period)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();

  /**
   * <code>int32 absences = 2;</code>
   */
  int getAbsences();

  /**
   * <code>string teacher = 3;</code>
   */
  java.lang.String getTeacher();
  /**
   * <code>string teacher = 3;</code>
   */
  com.google.protobuf.ByteString
      getTeacherBytes();

  /**
   * <code>double gps = 4;</code>
   */
  double getGps();

  /**
   * <code>string room = 5;</code>
   */
  java.lang.String getRoom();
  /**
   * <code>string room = 5;</code>
   */
  com.google.protobuf.ByteString
      getRoomBytes();
}
