// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.atakmap.android.sampledetailtester.proto;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.atakmap.android.sampledetailtester.proto.Student)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string firstname = 1;</code>
   */
  java.lang.String getFirstname();
  /**
   * <code>string firstname = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstnameBytes();

  /**
   * <code>string surname = 2;</code>
   */
  java.lang.String getSurname();
  /**
   * <code>string surname = 2;</code>
   */
  com.google.protobuf.ByteString
      getSurnameBytes();

  /**
   * <code>int32 grade = 3;</code>
   */
  int getGrade();

  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  java.util.List<com.atakmap.android.sampledetailtester.proto.Period> 
      getPeriodList();
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  com.atakmap.android.sampledetailtester.proto.Period getPeriod(int index);
  /**
   * <code>repeated .com.atakmap.android.sampledetailtester.proto.Period period = 4;</code>
   */
  int getPeriodCount();
}
